### PR TITLE
Add local search

### PR DESCRIPTION
**Pull request by EridianAlpha**
## Summary
Add local search to docs

## Details
It is possible to use Algolia but it will need someone to set up an account and apply as an Open Source project.

From: https://docusaurus.io/docs/search#using-algolia-docsearch
> The service is free for any open-source project: just make sure to read the [checklist](https://docsearch.algolia.com/docs/who-can-apply/) and [apply to the DocSearch program](https://docsearch.algolia.com/apply).

This PR shows an implementation using a local search tool: https://github.com/cmfcmf/docusaurus-search-local

Ticket:
https://github.com/ObolNetwork/obol-docs/issues/53

image

### CODE REVIEW

**Comment by EridianAlpha** [comment]
Using a new branch for Algolia.

**Comment by thomasheremans** [comment]
This already looks like a good first step. Not sure if possible but could you check if possible to align the search box branding with our docs theme (the black magnifier and grey background are a bit off-theme)

@OisinKyne what do you think of local search?

**Comment by EridianAlpha** [comment]
> This already looks like a good first step. Not sure if possible but could you check if possible to align the search box branding with our docs theme (the black magnifier and grey background are a bit off-theme)

@thomasheremans Yes it looks like the theme can be customized. I'll take a look.

**Comment by EridianAlpha** [comment]
@thomasheremans I've added the css to change the search bar colors background and icon for both dark and light themes. I wasn't sure exactly what colors you wanted to use, so I've used the same color for the magnifying glass as the heading text next to it.
image
image

**Review by OisinKyne — APPROVED** [review]
Amazing, looks great, tyvm!

**Pull request merged**
